spring.application.name=urlshortener

## App Config
app.base-url=http://localhost:8086
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=jdbc:postgresql://localhost:5433/url_shortener_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.user.name=Bags
spring.security.user.password=Bags
spring.security.user.roles=USER

server.port=8086