services:
  postgres:
    image: postgres:17
    container_name: urlshortener-postgres
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"

  spring-boot-url-shortener:
    image: bag0dock/urlshortener:latest
    container_name: spring-boot-url-shortener
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8086:8086"
    restart: unless-stopped
    depends_on:
      - postgres